# BoostPad Config file.
# Made by BoxOfDevs Team.

# Boost Block ID. ID list: http://minecraft-ids.grahamedgecombe.com/
Block: 237

# Boost Power
BoostPower: 3

# Enable or Disable Flame Particle.
Particle: true
